### ISSUE TITLE
No way to pass reader_options in the fluent method of pandass3datasource

### ISSUE THREAD

**Issue by Abhipank** [great-expectations/great_expectations#10078]
Basically in the batch request or runtimebatchrequest , we can pass , reader_options in batch_spec_passthrough .Such a function is not in the following case.

1. create a s3pandas data source using add_pandas_s3
2. then doing add_json_asset

In this steps , where to pass reader_method ?
basically , I want to pass following :-
```python
batch_spec_passthrough={
       "reader_method": "read_json",  
    "reader_options": {
          "lines": True
        }
```

The thing the file which I want to read a file which has many dictionaries(basically json records) separated by \n .but I cannot achieve it without passing reader_options .

**To Reproduce**
Please tell if it is possible , or accept it as a bug

**Expected behavior**
There  should be explicit description of such a thing in GX documentation if it is there or say no .

**Environment (please complete the following information):**
 - Operating System: macOS
 - Great Expectations Version: 0.18
 - Data Source: pandass3datasource
 - Cloud environment: AWS

**Comment by Kilo59** [comment]
I think you want to do what's in this doc, but use `.add_json()` instead of `.add_csv()`
https://docs.greatexpectations.io/docs/oss/guides/connecting_to_your_data/fluent/filesystem/connect_filesystem_source_data


```python
import great_expectations as gx

context = gx.get_context()

s3_datasource = context.sources.add_pandas_s3("my_datasource", bucket_name=..., boto3_options={...})

json_asset = s3_datasource.add_json_asset(name="my_asset", lines=True)

my_batch_request = json_asset.build_batch_request()
```

For more details on the parameter `.add_json_asset()` takes see below. They are more or less the exact same as `pandas.read_json()` takes.
https://github.com/great-expectations/great_expectations/blob/a3d2d210118900df24ca7f0cad9653c6b97cfd3f/great_expectations/datasource/fluent/pandas_s3_datasource.pyi#L243-L268

**Comment by Abhipank** [comment]
Thanks Gabriel . I was looking for it.
