### ISSUE TITLE
SparkDatasource Missing Arguments 

### ISSUE THREAD

**Issue by arjun-hareendran** [great-expectations/great_expectations#10265]
**Missing Argument in add_dataframe_asset method**
Our test cases are failing from today and was wondering if this is related to the new release. The documentation states the method accepts data frame as an input in the source code as well as documentation. The method definition states otherwise 

- spark_datasource.py
- https://docs.greatexpectations.io/docs/reference/api/datasource/fluent/SparkDatasource_class

**To Reproduce**
Running the below code in databricks results in the error 
```
import great_expectations as gx
import pyspark.sql.functions as F
from great_expectations.checkpoint import Checkpoint

# Input table details
REGION = "zzzz"
DATABASE_NAME = "yyyy"
TABLE = "xxx"
PROCESS_NAME = f"{DATABASE_NAME.lower()}_{TABLE}"

# Data Preparation
table_to_be_valdiated = spark.table(f"{DATABASE_NAME}.{TABLE}")


# Generate Context
context_root_dir = f"/zzzzz/{REGION}/{PROCESS_NAME}"
context = gx.get_context(context_root_dir=context_root_dir)

# Define type of soruce
dataframe_datasource = context.sources.add_or_update_spark(
    name=REGION,
)


# Define Assest for Great Expectations
dataframe_asset = dataframe_datasource.add_dataframe_asset(
    name=f"{PROCESS_NAME}",
    dataframe=table_to_be_valdiated,
)
```

**Expected behavior**
Add Data frame as an argument? 

**Environment (please complete the following information):**
 - Operating System: Databricks Notebook in Azure
 - Great Expectations Version: 1.0.0
 - Data Source: SparkDataSource
 - Cloud environment:  Azure, Databricks

**Comment by adeola-ak** [comment]
hi @arjun-hareendran I see where the confusion lies and I will be sure we get this updated. In the meantime, did you try to add that third argument, `batch_metadata` ?

**Comment by arjun-hareendran** [comment]
Hello @adeola-ak  : I will give it a try but for now I have opted for the version 0.18.19 . This lets me use the same format and execute the test cases.

**Comment by adeola-ak** [comment]
hi @arjun-hareendran, we won't be supporting 0.18 in the future, so I'd recommend migrating when you can. We do plan to get a migration guide out very soon. 

1.0 did introduce some breaking changes, largely around simplifying the interface, so I'd recommend checking out our updated documentation in the meantime at you convenience, which does outline the updated and simplified way to add spark data sources. 

I'll close this issue out for now as that error is expected due to updating our methods. Please be sure to reach out if you face more trouble that isn't outlined in our documentation. Thanks Arjun!
