### ISSUE TITLE
result_format and include_unexpected_rows does not work in expectation

### ISSUE THREAD

**Issue by Terma1** [great-expectations/great_expectations#10316]
**Describe the bug**
When I create a new expectation with a parameter result_format = {"result_format" : "COMPLETE", "include_unexpected_rows": True} , and then batch.validate(expectation), the result is default

**Expected behavior**
At the output I want to receive complete results and  table rows that do not correspond to the expectation (success false)

**Environment (please complete the following information):**
Databricks, i work with SparkDataframe

**Comment by adeola-ak** [comment]
without seeing your code, its quite hard to troubleshoot. what do you see when you change result format to BOOLEAN_ONLY?

`result_format = {"result_format" : "BOOLEAN_ONLY"}`

I want to understand if results_format is working for you at all

**Comment by Terma1** [comment]
Hi! Nothing changes. It seems that result_format doesn't work for me at all.

**Comment by adeola-ak** [comment]
my guess is you aren't passing the results format anywhere. we have a tip about this on this page of our [docs](https://docs.greatexpectations.io/docs/core/run_validations/run_a_validation_definition).

The tip is:
_You can set the level of detail returned in a Validation Definition's results by passing a Result Format configuration as the result_format parameter of your Validation Definition's run(...) method. For more information on Result Formats, see [Choose a result format](https://docs.greatexpectations.io/docs/core/trigger_actions_based_on_results/choose_a_result_format/)._

And here's an example of it being passed to a validation when it runs:

```
complete_result_format_dict = {"result_format" : "COMPLETE", "include_unexpected_rows": True}

validation_results = validation_definition.run(batch_parameters=batch_parameters, result_format=complete_result_format_dict)
```

I'll go ahead and close this issue for now since I'm unable to replicate it. I believe passing the results format should resolve the problem. If it doesn't, please don't hesitate to reach out again. Thank you!
