### ISSUE TITLE
TupleGCSStoreBackend removing every validation definition, regardless key

### ISSUE THREAD

**Issue by mw-otto** [great-expectations/great_expectations#10445]
**Describe the bug**
When deleting a validation definition from a store with TupleGCSStoreBackend backend it deletes every validation definition in the configured bucket.

**To Reproduce**
Add multiple validation definition with GCS backend and try to delete one of them. All will be deleted in the GCP bucket.

**Expected behavior**
I expected only the key to be deleted. If I look into into the source code of remove_key for the class TupleGCSStoreBackend there is no filter on the key at all. It just deletes every object in the bucket.

**Environment (please complete the following information):**
 - Great Expectations Version: 1.0.5
 - Cloud environment: GCP

**Comment by adeola-ak** [comment]
hi @mw-otto, thanks for reporting this. I’ve escalated the issue to the team, and will keep you updated on when the fix is made

**Comment by adeola-ak** [comment]
Hi there, @mw-otto - following up from last week. Unfortunately, we don’t currently support the GCS store backend nor do we have documentation for configuring a GCS backend for Validation Definitions. As a result, we’ll be removing this backend rather than fixing it.

We’ll be saving the files to disk using the standard FileSystem backend provider, allowing you to store them wherever you prefer. You can still use GCS to store your Great Expectations configuration, but going forward, you’ll need to manage that on your end. 

Thank you for understand and I apologize if this isn't the outcome you were hoping for.

**Comment by mw-otto** [comment]
Hey @adeola-ak, is there a way I can implement a custom backend by extending the TupleStoreBackend in our own code? I don't see any out-of-the-box plugin functionality.

**Comment by adeola-ak** [comment]
Yes, you can define a class that inherits from `great_expectations.data_context.store.store_backend.StoreBackend` and add it to `great_expectations.yml`. However, I currently don't have detailed guidance on that, so you would need to experiment with it without relying on out-of-the-box functionality. In the future, we may develop user guides on how to use GX Core with popular configuration management and storage tools, but I don't have a timeline for that yet.
