### ISSUE TITLE
empty data asset return success for expect_column_values_to_not_be_null expectation

### ISSUE THREAD

**Issue by tmilitino** [great-expectations/great_expectations#7432]
**Describe the bug**
when passing an empty data asset to use the `expect_column_values_to_not_be_null` expectations,  the test passes successfully for the column but the observed value renders an error as in the image below

![Captura de tela de 2023-03-23 01-33-12](https://user-images.githubusercontent.com/23370997/227105411-0053a1b1-f636-40a0-bf37-1ec670d8a7b6.png)

**To Reproduce**
1. create mass without row, only columns name
2. create a suite expectation with expect_column_values_to_not_be_null expectation
3. execute checkpoint
4. open data docs
5. see the result

**Expected behavior**
I believe is a false positive. the correct outcome for these situations is not "success"

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20.4
 - Great Expectations 15.50

**Comment by austiezr** [comment]
Hey @tmilitino ! Thanks for raising this. This is a subject we've discussed at length internally; the idea here is that the Expectation is intended to validate:

- "Are there rows containing null values?" 

rather than:

- "Are there rows, and do they contain null values?"

For example, this behavior is occasionally used to validate workflows where a given process or filter condition intentionally results in an empty asset & would otherwise return null values.

Closing this issue out for now as intentional behavior, but this is an ongoing conversation and we appreciate your view here!

**Comment by lucasarruda-ciandt** [comment]
Hi GX Team,

First, thank you for all your hard work on this project. I'd like to offer some constructive feedback based on my experience.

I've noticed a recurring pattern where the default behavior of some built-in Expectations differs from what might be a common user assumption, leading to the need for custom logic.

Two specific examples are:

ExpectColumnValuesToBeOfType: My initial expectation was that this would test for castability (i.e., can string '123' be cast to int?), but its actual function is to validate the type of an already-parsed column.

ExpectColumnValuesToNotBeNull: I expected this to fail on an empty dataset (since the condition of "all values are not null" isn't met), but it currently passes.

These behaviors suggest that GX has a clear, principled design philosophy for these edge cases. While I respect this, it can create friction. The current solution is to build a Custom Expectation, but this presents a few challenges:

High Barrier to Entry: Creating Custom Expectations is one of the more advanced features of GX and can be a hurdle for newer users or engineers less focused on deep Python development.

Adoption Friction: This steep learning curve is a recurring theme in community discussions (e.g., on Reddit) where some users struggle to get value from GX.

Suggestion:

Would you consider adding optional parameters to built-in Expectations to support these alternative validation paths? For example:

ExpectColumnValuesToBeOfType(..., check_castability=True)

ExpectColumnValuesToNotBeNull(..., allow_empty=False)

I believe introducing this kind of flexibility would make GX more intuitive, lower the barrier for adoption, and empower users to solve common use cases without needing to immediately create custom classes or searching for other solutions.

Thanks for considering this feedback. I'm happy to discuss it further.
