### ISSUE TITLE
GE loops thru ALL expectation_suites in expectations directory when you run ANY checkpoint

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7800]
**Describe the bug**

GE loops thru ALL expectation_suites in expectations directory (with subdirectories) when you run a single checkpoint

It is:
- not needed
- **risky**: one bug in one expectation_suite will cause GE to fail running any checkpoint (see below)
- it **slows down** the startup time (depends on how many expectation_suites you have)

**To Reproduce**

1. Edit one of your expectation_suites - add something into meta field:

"meta": {"some text with no key value pair here"},

2. run your checkpoint. 

**ANY** checkpoint with **NO connection** to your modified expectation_suite will fail with very descriptive error in GE CLI:

Expecting ':' delimiter: line xx column yy (char zz)

After debugging in PyCharm (or see Airflow log) you will find it happens in python3.10/json/decoder.py at line 353 when parsing your modified expectation_suite

**Expected behavior**

1) Do not loop thru all expectation_suites!
2) At least a clear and concise description of error is expected!

**Environment (please complete the following information):**
 - Operating System:  Linux,
 - Great Expectations Version:  0.16.3 and .8

**Comment by austiezr** [comment]
Hey @kujaska ! Thanks for raising this. We'll investigate this behavior and be in touch.

**Comment by billdirks** [comment]
Thanks for reporting this issue. Currently we require all configured expectation suites to be well formed json. This is because we use data inside the json file to refer to an expectation suite (the value referred to by the `expectation_suite_name` key) and, therefore, need to parse these files when we are searching for the suite a user is requesting. We don't want to skip malformed json files and return saying an expectation suite doesn't exist when it exists but is ill formatted. In light of this current architecture, we don't plan on fixing this issue at this time.

**Comment by helloimowen** [comment]
Hi - is this relevant to the s3 store as well? I'm investigating why running GX in some of my environments is 6-10x slower than running in others. The slower environments have more expectation suites and checkpoint definitions in the s3 store (~450 in the slow environments, ~20 in the fast one). Why parse all expectation suites when the expectation_suite_name is the filename?
