### ISSUE TITLE
Render asset profile in databricks

### ISSUE THREAD

**Issue by easonktsai** [great-expectations/great_expectations#7853]
I enconter the same issue with this post [stackoverflow post](https://stackoverflow.com/questions/68414605/great-expectation-profiling-on-sparkdf-takes-a-long-time-when-there-are-many-col) 

When my dataframe with many column(100+), rendering asset profile took long time. Is there any solution to fix this?

Thanks.

**Comment by tjholsman** [comment]
Hi @easonktsai, could you share your config and the code you're using to call the profiler? Also please include your GX version and OS information. Thanks!

**Comment by easonktsai** [comment]
Hi @tjholsman 

GX version: 0.16.10
databricks runtime version: 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)

Here is code snippets
```py
df_ge = ge.dataset.SparkDFDataset(df)

BasicDatasetProfiler.profile(df_ge)
```

use spark to read csv or parquet to df and then run the snippets above.
It will take long time to render.

Thanks.

**Comment by tjholsman** [comment]
Thanks @easonktsai. I can see that you are using the older V2 API. Since v0.14 the preferred way of using GX is through the V3 API. I'd recommend that you consider [migrating to V3](https://docs.greatexpectations.io/docs/guides/miscellaneous/migration_guide) since we do not intend to work on performance improvements for V2. 

It's worth keeping in mind that each additional column in your data represents many potential expectations, which computationally can be very expensive. You may find it useful to exclude columns on particular runs of the profiler, or to downsample the data prior to profiling.
