### ISSUE TITLE
Please update pandas dependency

### ISSUE THREAD

**Issue by stefaneidelloth** [great-expectations/great_expectations#7887]
great-expectations 0.16.12 requires pandas<2.0.0,>=1.3.0; python_version >= "3.10", but you have pandas 2.0.1 which is incompatible.

**Comment by tjholsman** [comment]
Hi @stefaneidelloth, thanks for reaching out! Where are you seeing pandas 2.0.1 referenced?

**Comment by stefaneidelloth** [comment]
The above output comes from pip package manager, trying to install great_expectations after installing pandas 2.0.1.
Also see your requirements.txt file:
https://github.com/great-expectations/great_expectations/blob/develop/requirements.txt

**Comment by tjholsman** [comment]
@stefaneidelloth Thanks! We had to pin pandas to < 2.0.0 due to issues with other dependent libraries. From requirements.txt:

`# Note: Pandas set to less than 2.0.0 as of 2023-04-05 due to incompatibilities with Altair and Metrics`

Is there functionality in pandas 2.0.1 that you require in your GX environment?

**Comment by tjholsman** [comment]
Hi @stefaneidelloth I'll be closing this but please let us know if you have more information or need anything else.
