### ISSUE TITLE
Cannot init in cmd as access denied

### ISSUE THREAD

**Issue by GrandJagon** [great-expectations/great_expectations#8051]
Hello everybody.

I have just installed great_expectations as I am doing  data profiling for a database and that seems the perfect tool, however I have some issue.

I use python3.11 on windows 11, I successfully installed great_expectations in a python virtual_environement. I've tried to run a quick validation against a CSV file by providing a hardcoded configuration for batch and validator within the python code.

Now that I am settled I want to create a project and start working and my data profling but whenver I try to init the framework with 'great_expectations init' I got the error message 'access denied'.

I've tried toher commands such as --help or just even launching the .exe file and every time I have the same error message. I also tried to mitigate it while lauching the cmd and the application in admin mode but it does not change anything.

Has anyone ever encountered this issue ? What could I do to fix it ?

Thank you in advance !!

**Comment by austiezr** [comment]
Hey @GrandJagon! Thanks for reaching out.

GX doesn't officially support Windows or Python 3.11 -- it's possible that there may be some instability on those platforms that prevents functionality.

However, following something like [this workflow](https://docs.greatexpectations.io/docs/tutorials/quickstart/) rather than utilizing the CLI may circumvent many of these issues, allowing you to use GX.

Would you be willing to elaborate on 

> I am doing data profiling for a database and that seems the perfect tool

and how you'd like to use GX in that use-case?

**Comment by GrandJagon** [comment]
Hey @austiezr thank you for your swift reply !

I didn't know about the compatibiliy issue with windows and python, I will try to downgrade my python virtual environement then !

I ma currently planning a data migration and as a part of it I will check the databases columns against some simple data quality rules to include a data cleasing option.

I would like to use GX to find if columns content follow some rules and formatting (no duplicate, phone and addresses properly formatted and average/mean etc for the numerical values...)

**Comment by austiezr** [comment]
Thanks @GrandJagon ! Closing this out for now; feel free to re-open if needed!
