### ISSUE TITLE
Stop recommending to use VALIDATOR on production?

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#8080]
In this Monthly Community video https://www.youtube.com/watch?v=vJjND3YMSvA&t=2729s around time [32:13] (https://www.youtube.com/watch?v=vJjND3YMSvA&t=1933s) a **validator** is proposed to be used as a good approach to create expectations suite on the fly on production. 

But it means that you will RUN your checks actually TWICE:

- once running validator (one expectation at a time)

- next running checkpoint (all expectations from the suite)

This way you actually touch your data TWICE, and for BIG tables it might be COSTLY

**Comment by austiezr** [comment]
Hey @kujaska ! Thanks for raising this. 

Using a Validator is very common during the initial creation of Expectation Suites, particularly for users who want or need immediate feedback on the relationship of their data to the expectations being placed, and users who are newer to GX workflows and expectations. This is also a very common workflow for users who are explicitly & intentionally working in-memory, as in the above video.

Validators are *never* a requirement, nor a recommendation, for repeated production workflows where an Expectation Suite can be persisted and re-used, and the above video does indicate that you can (and may want to) persist your suite to disk rather than creating suites on the fly at around 32:23. Ultimately, we leave it up to our users to determine which workflows are best for them, and to understand the costs of interaction with their data, whether via GX or another tool.
