### ISSUE TITLE
Access to Trino source used unexpected credentials for authorization

### ISSUE THREAD

**Issue by Stefs-2142** [great-expectations/great_expectations#8201]
**Describe the bug**
Instead of using credentials defined in DataSource config for Trino source called `trino_datasource_config`, GE trying to use my local Linux user name- **sbubnov**.

While running example bellow got next error - 
```
File "/home/sbubnov/s7/projects/ge/env/lib/python3.8/site-packages/trino/client.py", line 613, in raise_response_error
    raise exceptions.HttpError(
trino.exceptions.HttpError: error 401: b'Access Denied: User [sbubnov] not a member of an authorized group'
```
i assume that Trino connector broken (

**To Reproduce**
in my build i use EphemeralDataContext. Bellow code that i used.
1. define script.
```
    datasources_name = 'Glacier_UAT_2'
    connection_string = f"trino://{user}:{password}@{host}:{port}/{database}"
    data_context_config = DataContextConfig(
        config_version=3,
        store_backend_defaults=InMemoryStoreBackendDefaults()
    )
    trino_datasource_config = {
        'name': datasources_name,
        "class_name": "Datasource",
        "execution_engine": {
            "class_name": "SqlAlchemyExecutionEngine",
            "connection_string": connection_string,
        },
        "data_connectors": {
            "default_configured_data_connector_name": {
                "class_name": "ConfiguredAssetSqlDataConnector",
                'assets': {
                    "test11": {
                        "class_name": "Asset",
                        "schema_name": "samples",
                        "table_name": "test11",
                    },
                }
            },
        },
    }

    context = EphemeralDataContext(project_config=data_context_config)
    context.add_datasource(**trino_datasource_config)

    suite = context.add_expectation_suite(
        expectation_suite_name='trino_test',
        expectations=[
            ExpectationConfiguration(
                expectation_type="expect_column_values_to_be_in_set",
                kwargs={
                    "column": "accelerated",
                    "value_set": ['true', 'false'],
                },
            ),
        ]
    )
    context.save_expectation_suite(expectation_suite=suite)

    trino_batch_request = {
        'data_connector_name': 'default_configured_data_connector_name',
        "datasource_name": datasources_name,
        "data_asset_name": "test11",
    }

    checkpoint = ge.checkpoint.SimpleCheckpoint(
        name="trino_test",
        data_context=context,
        expectation_suite_name="trino_test",
        batch_request=trino_batch_request,
    )
    context.add_checkpoint(checkpoint=checkpoint)

    datahub_action = {
        "name": "datahub_action",
        "action": {
            "module_name": "datahub.integrations.great_expectations.action",
            "class_name": "DataHubValidationAction",
            "server_url": datahub_host,
            "token": datahub_password,
        }
    }

    checkpoint = context.get_checkpoint("trino_test")
    checkpoint.action_list.append(datahub_action)

    print('Run Great Expectation task...')
    checkpoint_result = checkpoint.run()

    if not checkpoint_result["success"]:
        print("Validation failed!")
    else:
        print("Validation succeeded!")
```
2. run script

**Expected behavior**
output print - "Validation succeeded!"

**Environment (please complete the following information):**
 - Operating System:  Linux Mint 20.2
 - Great Expectations Version: 0.17.1
 - Datasource: Trino
 - Cloud environment: None

**Additional context**
user - sbubnov that linux user on my laptop

**Comment by HaebichanGX** [comment]
Hi @Stefs-2142 I put this in our backlog, as I mentioned in our discussions on slack, we don't officially support Trino so we'll try our best but don't have docs for this specifically. I'll try to take a look once I have time.

**Comment by Stefs-2142** [comment]
@HaebichanGX, got it) 
Thanks anyway!

**Comment by YuriyGavrilov** [comment]
+1

**Comment by maxpoulain** [comment]
Hi ! 

My configuration:

- Trino version: 422
- Trino configuration:
    -  HTTPS
    - Port 8443 instead of 443
    - LDAP password for authentication
- Great expectation: 0.15.50 & 0.17.9

I think, I have a similar issue as described before.. 
I have a Trino cluster using HTTPS port 8443 and when I try with following `connection_string` I got an issue `error: error 401: b'Access Denied: Invalid credentials'` but my credentials are good and I can connect to my cluster and launch requests from Trino CLI and using SQLAlchemy in Python ! 

Here is our `connection_string`:
```yaml
connection_string: trino://<MY_USERNAME>:${TRINO_PASSWORD}@<OUR_TRINO_HOST>:8443/<OUR_CATALOG>
```

I think Great Expectation is not handling correctly connection using `BasicAuthentication` because using SQLAlchemy in Python I need to import from `trino.auth` the `BasicAuthentication`  and then add some extra parameter to setup a connection to Trino (as described here: https://github.com/trinodb/trino-python-client/blob/master/README.md):
```python
from trino.auth import BasicAuthentication
from sqlalchemy import create_engine

eng = create_engine('trino://<MY_USERNAME>@<OUR_TRINO_HOST>:8443/<OUR_CATALOG>', connect_args={'http_scheme': 'https', "auth": BasicAuthentication(<MY_USERNAME>, <MY_PASSWORD>),})
```
I think it's not the case in Great Expectations so the connection cannot be setup. Or maybe I'am wrong and it's another issue.

Also, I'm sorry but I don't understand why Trino is not officially supported by Great Expectation as there is a page dedicated to it in version 0.15.50 ( https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/database/trino/) and in version 0.17.9 Trino is explicitly mentioned (https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data/). So, is it only like basic Trino configuration (without password for example) that is supported by great expectation for now and maybe in the future all Trino configuration are going to be supported ? 

Thanks in advance for your help !

**Comment by molliemarie** [comment]
Hello @Stefs-2142. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
