### ISSUE TITLE
Unable to Integrate with Airflow 2.6.2

### ISSUE THREAD

**Issue by HadasManor** [great-expectations/great_expectations#8504]
Description:
I am using Airflow 2.6.2 and trying to upgrade great expectations from 0.15.44 to 0.17.6

Airflow requires version 8.1.4 of Click package, which was limited to 8.1.3 in the newer GX versions.

```
ERROR: Cannot install great-expectations==0.17.6 because these package versions have conflicting dependencies.
The conflict is caused by:
great-expectations 0.17.6 depends on Click<=8.1.3 and >=7.1.2
The user requested (constraint) click==8.1.4
```

**Comment by itaise** [comment]
And here are the constrains for Airflow 2.6.2 + python 3.10:
https://raw.githubusercontent.com/apache/airflow/constraints-2.6.2/constraints-3.10.txt

**Comment by billdirks** [comment]
Thanks for bringing this to our attention. I've removed the upper bound on Click in [this PR](https://github.com/great-expectations/great_expectations/pull/8515/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R2) which should ship with our next release later this week. We still disallow 8.1.4 because of [this typing bug](https://github.com/pallets/click/issues/2558) in `Click` but it looks like it's resolved it in 8.1.5.

**Comment by itaise** [comment]
Hi, 
thanks a lot for the PR!
the thing is, that in Airflow constraints for version 2.6.3 (latest airflow) the specific version of click==8.1.4 is required. 
https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt
What would you recommend to do to make GX work with 2.6.3?
Thanks!

**Comment by HaebichanGX** [comment]
Since this issue is tied to the PR bill mentioned and it's merged, I will close out this issue
