### ISSUE TITLE
Observe unexpected queries when using `expect_column_max_to_be_between` expectation

### ISSUE THREAD

**Issue by Long-Nguyen-Paidy** [great-expectations/great_expectations#8797]
**Describe the bug**
When checking our data using `expect_column_max_to_be_between`, we observe that it takes too long time.
We then check which queries does GE trying to run, and here is the list:
#1
`SELECT * FROM test_table`

#2
`SELECT count(*) AS "table.row_count" 
FROM (
    SELECT *
    FROM test_table
    ) AS anon_1`

#3
`SELECT max(created_at) AS "column.max" 
FROM (
    SELECT *
    FROM test_table
    ) AS anon_1`

May I ask is this a normal behavior ? 
We expected that only last one should be executed. Let 's image if we run this check over a large table, the first query could run forever...
And what we should config to avoid this ?

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.17.7
 - Data Source: PostgreSQL
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**

**Comment by rachhouse** [comment]
Hi @Long-Nguyen-Paidy, thanks for reaching out! I'm looking into this issue.

**Comment by rachhouse** [comment]
Hey @Long-Nguyen-Paidy, could you please share your code that results in these three queries to the postgres database?

**Comment by Long-Nguyen-Paidy** [comment]
hello @rachhouse , thanks for reply !

Here I put some simple codes to reproduce, basically we try to setup a Postgres datasource with a `RuntimeDataConnector`.
```
ge_context_config = DataContextConfig(
        datasources={
            "postgres": DatasourceConfig(
                class_name="Datasource",
                execution_engine={
                    "class_name": "SqlAlchemyExecutionEngine",
                    "credentials": db_creds,
                    "create_temp_table": False
                },
                data_connectors={
                    "query_connector": {
                        "class_name": "RuntimeDataConnector",
                        "batch_identifiers": ["year", "month", "day", "hour"]
                    },
                }
            ),
        },
        store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=ge_local_dir),
)

context = gx.get_context(project_config=ge_context_config)
```

Then try to run a `Validator` to check a `RuntimeBatchRequest` with a custom query over a `ExpectationSuite` with only `expect_column_max_to_be_between` expectation.
```
test_query = "SELECT * FROM public.test"

batch_request = RuntimeBatchRequest(
    datasource_name="postgres",
    data_connector_name="query_connector",
    data_asset_name="public_test_table",
    runtime_parameters={"query": test_query},
    batch_identifiers={
        "year": 2023,
        "month": 1,
        "day": 1,
    },
)

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name='test_suite'
)

validator.validate()
```

While Validator is running, we monitor which queries are being ran and found those in my original post.

**Comment by rachhouse** [comment]
Hey @Long-Nguyen-Paidy, I've looked into this, and confirmed that query no. 2 and 3 are executed when the `expect_column_max_to_be_between` Expectation is run. From what I found, there's not a way to turn off either of these queries. However, query no. 2 shouldn't be a substantial performance concern as the `select count(*)` uses an index only scan, and query no. 3 is necessary to gather the column max metric for the expectation.

I think the reason you're seeing the `select *` (query no. 1) executed is due to your implementation with the RuntimeBatchRequest, as it's being supplied directly in the `runtime_parameters`. Data Connectors and RuntimeBatchRequests are an older approach to using GX, I'd recommend trying the current Fluent Data Source (FDS) method to see if you still run into this problem.

Our current [Get started with Great Expectations and SQL doc](https://docs.greatexpectations.io/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql) will walk you through connecting to your postgres table using FDS. 

As another example, here's the code I used when investigating this issue - I ran it against a dockerized Postgres instance and only query no. 2 and 3 were executed on the database, not the `select *`:
```
import great_expectations as gx

context = gx.get_context()

datasource = context.sources.add_sql(
    name="my_datasource", 
    connection_string="postgresql://example_user@db/gx_example_db",
    create_temp_table=False,
)

table_asset = datasource.add_table_asset(
    name="my_taxi_data",
    table_name="nyc_taxi_data"
)

batch_request = table_asset.build_batch_request()

expectation_suite_name = "my_expectation_suite"
context.add_or_update_expectation_suite(expectation_suite_name=expectation_suite_name)

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name,
)

validator.expect_column_max_to_be_between(
    "passenger_count", min_value=1, max_value=10,
)

checkpoint = context.add_or_update_checkpoint(
    name="checkpoint",
    validator=validator,
)

validator.save_expectation_suite(discard_failed_expectations=False)

checkpoint_result = checkpoint.run()
```

**Comment by Long-Nguyen-Paidy** [comment]
@rachhouse Thanks for your information.

I have tried and confirm that query No.1 is not executed as expected. That's interesting RuntimeBatchRequest is the root cause.
However, when using new Fluent Datasource, with a splitter on a column, we observe that this query is ran when Validator is initialized:
```
SELECT 
    distinct(concat(concat(concat(concat('', CAST(EXTRACT(year FROM created_at) AS VARCHAR)), CAST(EXTRACT(month FROM created_at) AS VARCHAR)), CAST(EXTRACT(day FROM created_at) AS VARCHAR)), CAST(EXTRACT(hour FROM created_at) AS VARCHAR))) AS concat_distinct_values,
            CAST(EXTRACT(year FROM created_at) AS INTEGER) AS year,
            CAST(EXTRACT(month FROM created_at) AS INTEGER) AS month,
            CAST(EXTRACT(day FROM created_at) AS INTEGER) AS day,
            CAST(EXTRACT(hour FROM created_at) AS INTEGER) AS hour
FROM public.test;
```
This query could run forever in a big table, since it does not use any index, sorry because it may not related to original topic here, but do we have any extra config that could be used to limit data scan, or speed it up ?

**Comment by rachhouse** [comment]
Hi @Long-Nguyen-Paidy, there's currently no GX config that can be used to control or alter the query that assembles the batch identifiers based on the splitter column. 

Out of interest, which splitter method are you using? I see the query is pulling the hour from the `created_at` field, but for Postgres tables, I'm not aware of a splitter that uses hour.

**Comment by Long-Nguyen-Paidy** [comment]
hi @rachhouse I 'm using `add_splitter_datetime_part` splitter, with `datetime_parts=["year", "month", "day", "hour"]`.

**Comment by rachhouse** [comment]
@Long-Nguyen-Paidy Ah, thanks for letting me know!

I think we've resolved this issue to the extent possible  - investigating queries running underneath the hood for expectations and diagnosing the `RuntimeBatchRequest` behavior. I'm going to go ahead and close out this issue, please reply if you think otherwise and we can reopen.
